l_english:
########################################################
### KEEP THESE IN THE SAME ORDER AS THE VANILLA FILE ###
########################################################

#changed to British spelling
 PRODUCTION_MATERIALS_ALUMINIUM: "Aluminium"
 PRODUCTION_VEHICLES_BUTTON: "Build Armoured Vehicles"
 PRODUCTION_VEHICLES_BUTTON_DISABLED: "Armoured Vehicles are §RNot invented§!!"
 PRODUCTION_ARMOR_FILTER: "Armoured Vehicles"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL_SIMPLE: "§HLicence production§!: $VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL: "§HLicence production factory output§!\nTotal: $VALUE|+%$\nBreakdown:"
 LICENSED_EQUIPMENT_TECH_SPEED_REDUCTION: "§YLicence technology difference§!:\n Base: $BASE|+%$\n Modified total: $TOTAL|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_MODIFIER: "§YLicence modifier§!:\n Base: $BASE|+%$\n Modified total: $TOTAL|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NOT_FACTION: "§YNot in faction with licenser§!: $VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NO_LICENSE: "§YNo active licence§!: $VALUE|+%$"
 LICENSED_PURCHASE_CIC_COST: "§YThis licence costs§!: £civ_factory $AMOUNT|Y$"
