-- Kaiserreich defines values

NDefines.NGame.END_DATE = "1959.1.1.1"
NDefines.NGame.MAJOR_PARTICIPANTS_FOR_MAJOR_WAR = 20
NDefines.NDiplomacy.MAX_OPINION_VALUE = 200
NDefines.NDiplomacy.MIN_OPINION_VALUE = -200
NDefines.NDiplomacy.BASE_PEACE_PUPPET_FACTOR = 0
NDefines.NDiplomacy.BASE_PEACE_LIBERATE_FACTOR = 0
NDefines.NDiplomacy.VERY_GOOD_OPINION = 100
NDefines.NDiplomacy.VERY_BAD_OPINION = -100
NDefines.NDiplomacy.VOLUNTEERS_DIVISIONS_REQUIRED = 15 		-- Vanilla is 30 do we change?
NDefines.NDiplomacy.PEACE_SCORE_PER_PASS = 0.75
NDefines.NDiplomacy.AUTONOMY_LEVEL_CHANGE_PP_ANNEX = 10000
NDefines.NDiplomacy.AUTONOMY_LEVEL_CHANGE_PP_FREE = 10000
NDefines.NCountry.EVENT_PROCESS_OFFSET = 5
NDefines.NCountry.POLITICAL_POWER_CAP = 400.0
NDefines.NCountry.STATE_OCCUPATION_COST_MULTIPLIER = 0.25	-- Vanilla is 0.01
NDefines.NCountry.CAPITULATE_STOCKPILES_RATIO = 0.75
NDefines.NPolitics.BASE_POLITICAL_POWER_INCREASE = 1
NDefines.NTrade.ALLOW_TRADE_CUT_OFF = 50
NDefines.NWiki.BASE_URL = "http://kaiserreich.wikia.com/wiki/The_Kaiserreich_Wiki"
NDefines.NGraphics.COUNTRY_FLAG_SMALL_TEX_WIDTH = 11
NDefines.NGraphics.COUNTRY_FLAG_TEX_MAX_SIZE = 512
NDefines.NGraphics.COUNTRY_FLAG_SMALL_TEX_MAX_SIZE = 128
NDefines.NGraphics.COUNTRY_FLAG_STRIPE_TEX_MAX_WIDTH = 11
NDefines.NGraphics.COUNTRY_FLAG_STRIPE_TEX_MAX_HEIGHT = 4096
NDefines.NGraphics.COUNTRY_FLAG_LARGE_STRIPE_MAX_HEIGHT = 12400

-- Vanilla+ defines values

--NDefines.NCountry.LOCAL_MANPOWER_ACCESSIBLE_NON_CORE_FACTOR = 0.05 		-- Vanilla is 0.02
--NDefines.NCountry.MAJOR_MIN_FACTORIES = 50 								-- Vanilla is 35
--NDefines.NProduction.BASE_FACTORY_SPEED_MIL = 2.5							-- Vanilla is 5
--NDefines.NBuildings.AIRBASE_CAPACITY_MULT = 100							-- Vanilla is 200
--NDefines.NMilitary.FIELD_MARSHALL_CAP = 72								-- Vanilla is 0
--NDefines.NMilitary.BASE_COMBAT_WIDTH = 96									-- Vanilla is 80
--NDefines.NMilitary.ADDITIONAL_COMBAT_WIDTH = 48							-- Vanilla is 40
--NDefines.NMilitary.MAX_NUM_TRAITS = 3										-- Vanilla is 6
--NDefines.NMilitary.PLAN_EXECUTE_CAREFUL_MAX_FORT = 3						-- Vanilla is 5
--NDefines.NMilitary.NUKE_MIN_DAMAGE_PERCENT = 0.75							-- Vanilla is 0.1
--NDefines.NMilitary.NUKE_MAX_DAMAGE_PERCENT = 1.0							-- Vanilla is 0.9
--NDefines.NMilitary.DISBAND_MANPOWER_LOSS = 0.75							-- Vanilla is 0.7
--NDefines.NMilitary.MIN_DIVISION_DEPLOYMENT_TRAINING = 0.5					-- Vanilla is 0.2
--NDefines.NMilitary.FRONT_MIN_PATH_TO_REDEPLOY = 25						-- Vanilla is 8
--NDefines.NAir.COMBAT_MAX_WINGS_AT_ONCE_PORT_STRIKE = 400					-- Vanilla is 10000
--NDefines.NAir.BASE_STRATEGIC_BOMBING_HIT_SHIP_DAMAGE_FACTOR = 15			-- Vanilla is 50
--NDefines.NNavy.DETECTION_CHANCE_MULT_FORMATION_SPREAD_CONVOY_RAIDING = 1.6	-- Vanilla is 1.2
--NDefines.NNavy.COMBAT_MIN_WIN_CHANCE_TO_KEEP_FIGHTING = 0.6				-- Vanilla is 0.2
--NDefines.NNavy.COMBAT_CLOSE_DISTANCE_MAX_HIT_CHANCE_BONUS = 0.3			-- Vanilla is 0
--NDefines.NNavy.COMBAT_DAMAGE_RANDOMNESS = 0.6								-- Vanilla is 0.3
--NDefines.NNavy.COMBAT_DAMAGE_REDUCTION_ON_RETREAT = 0.5					-- Vanilla is 0.8
--NDefines.NNavy.COMBAT_ESCAPING_SPEED_BALANCE = 0.7						-- Vanilla is 0.8
--NDefines.NNavy.COMBAT_MAX_DISTANCE_TO_ARRIVE = 160						-- Vanilla is 80
--NDefines.NNavy.COMBAT_MIN_DURATION = 18									-- Vanilla is 8
--NDefines.NNavy.COMBAT_BASE_CRITICAL_CHANCE = 0.2							-- Vanilla is 0.1
--NDefines.NNavy.REPAIR_AND_RETURN_PRIO_LOW = 0.4							-- Vanilla is 0.2
--NDefines.NNavy.REPAIR_AND_RETURN_PRIO_MEDIUM = 0.6						-- Vanilla is 0.5
--NDefines.NNavy.EXPERIENCE_FACTOR_CONVOY_ATTACK = 2						-- Vanilla is 0.05
--NDefines.NNavy.EXPERIENCE_FACTOR_CARRIER_GAIN = 0.01						-- Vanilla is 0.1
--NDefines.NNavy.NAVY_VISIBILITY_BONUS_ON_RETURN_FOR_REPAIR = 1.3			-- Vanilla is 0.9
--NDefines.NNavy.NAVAL_SUPREMACY_INTEL_LOW = 0.5							-- Vanilla is 0.3
--NDefines.NNavy.NAVAL_SUPREMACY_CAN_INVADE = 0.8							-- Vanilla is 0.5
--NDefines.NNavy.SEA_AIR_COMBAT_MAX_WINGS_ON_STACK = 400					-- Vanilla is 200
NDefines.NAI.DIPLOMACY_ACCEPT_VOLUNTEERS_BASE = 75							-- Vanilla is 50
NDefines.NAI.RESEARCH_BONUS_FACTOR = 10.0									-- Vanilla is 0.9
NDefines.NAI.NAVAL_DOCKYARDS_SHIP_FACTOR = 2.5								-- Vanilla is 1.5
NDefines.NAI.NAVAL_BASES_SHIP_FACTOR = 1.25									-- Vanilla is 0.75
NDefines.NAI.NAVAL_STATES_SHIP_FACTOR = 0.25								-- Vanilla is 0.75
NDefines.NAI.DEPLOY_MIN_TRAINING_PEACE_FACTOR = 1.0							-- Vanilla is 0.95
NDefines.NAI.DEPLOY_MIN_EQUIPMENT_PEACE_FACTOR = 1.0						-- Vanilla is 0.95 
NDefines.NAI.DEPLOY_MIN_EQUIPMENT_WAR_FACTOR = 1.0							-- Vanilla is 0.90
NDefines.NAI.LENDLEASE_FRACTION_OF_PRODUCTION = 0.25						-- Vanilla is 0.5
--NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_LOW = 0.9							-- Vanilla is 0.85
--NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_LOW = 0.65						-- Vanilla is 0.4
--NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_MED = 0.7							-- Vanilla is 0.75
--NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_MED = 0.45						-- Vanilla is 0.3
--NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_HIGH = 0.5							-- Vanilla is 0.2
--NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_HIGH = 0.25					-- Vanilla is 0.15
NDefines.NAI.RESERVE_TO_COMMITTED_BALANCE = 0.25							-- Vanilla is 0.1
NDefines.NAI.MAIN_ENEMY_FRONT_IMPORTANCE = 7.5								-- Vanilla is 4.0
--NDefines.NAI.ORG_UNIT_STRONG = 0.8											-- Vanilla is 0.9
--NDefines.NAI.ORG_UNIT_WEAK = 0.5											-- Vanilla is 0.15
--NDefines.NAI.STR_UNIT_STRONG = 0.6											-- Vanilla is 0.75
--NDefines.NAI.STR_UNIT_WEAK = 0.25											-- Vanilla is 0.2
--NDefines.NAI.PLAN_FACTION_WEAK_TO_ABORT = 0.55								-- Vanilla is 0.65
--NDefines.NAI.PLAN_AVG_PREPARATION_TO_EXECUTE = 0.6						-- Vanilla is 0.5
NDefines.NAI.AIR_WING_REINFORCEMENT_LIMIT = 300								-- Vanilla is 150
NDefines.NAI.UPGRADE_PERCENTAGE_OF_FORCES = 0.65							-- Vanilla is 0.1
NDefines.NAI.NAVAL_MISSION_MIN_FLEET_SIZE = 5								-- Vanilla is 3
NDefines.NAI.NAVY_PREFERED_MAX_SIZE = 15									-- Vanilla is 20
NDefines.NAI.MAX_DISTANCE_NALAV_INVASION = 600.0							-- Vanilla is 200
NDefines.NAI.ENEMY_NAVY_STRENGTH_DONT_BOTHER = 1.25							-- Vanilla is 2.5
NDefines.NAI.PRODUCTION_MAX_PROGRESS_TTO_SWITCH_NAVAL = 5.0					-- Vanilla is 0.3
NDefines.NAI.MAX_UNITS_FACTOR_AREA_ORDER = 1.5								-- Vanilla is 1.0
NDefines.NAI.DESIRED_UNITS_FACTOR_AREA_ORDER = 1.5							-- Vanilla is 1.0
NDefines.NAI.MAX_UNITS_FACTOR_FRONT_ORDER = 2.0								-- Vanilla is 1.5
NDefines.NAI.MAX_UNITS_FACTOR_INVASION_ORDER = 1.5							-- Vanilla is 1.0
NDefines.NAI.FRONT_UNITS_CAP_FACTOR = 25.0									-- Vanilla is 15.0

